name: purchases_dart
description: "A pure Dart implementation of purchases_flutter (aka RevenueCat)."
version: 1.0.6
homepage: https://navideck.com
repository: https://github.com/Navideck/purchases_dart
issue_tracker: https://github.com/Navideck/purchases_dart/issues
funding:
  - https://github.com/sponsors/Navideck

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  purchases_flutter: ^9.2.1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
